chinese:
#    users:
#        - cctvch
    playlists:
        luyu-official: https://www.youtube.com/watch?v=6GOTZa3xU2U&list=PL0qv-SqUbwqVVIabi_90Me4UeuKWs1Sbn

english:
#    users:
#        - cnn
    playlists:
        ellen-show: https://www.youtube.com/watch?v=s0MbQWhyoD0&list=PLuW4g7xujBWeiOJ-C-pZCTdUMWucxeMNQ
